# ---------- Build Stage ---------- 

# we are using here node:22-alpine image ::>>
FROM node:22-alpine AS builder

# using inside the container
WORKDIR /app

# Copy dependency files ::>> copy package.json and package-lock.json
COPY package*.json ./

# Install deps /// install the dependency:: >> fixed and cached:::>>
RUN npm install 

# Copy rest of frontend :: copy code 
COPY . .

# Build Vite app :: build vite app :: npm run build
RUN npm run build


# ---------- Production Stage ----------
FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Add custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built files from builder
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

